sudo: false
language: node_js
node_js:
  - 8

cache: yarn

install:
  - yarn global add lerna jest
  - yarn install
  - lerna bootstrap

script:
  - yarn test
  - yarn build

after_success:
  - yarn cov:send