service: microgamma-groups-service # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2

  environment:
    MONGOURI: ${env:MONGODB_ATLAS_CLUSTER_URI, 'mongodb://192.168.254.2:27017/test'}
    DEBUG: ${env:DEBUG, ''}
    SECRET: ${env:SECRET, 'my-secure-secret'}

  apiGateway:
    restApiId:
      Fn::ImportValue: 'apiGateway-restApiId'
    restApiRootResourceId:
      Fn::ImportValue: 'apiGateway-rootResourceId'

plugins:
  - serverless-plugin-monorepo
  - '@microgamma/serverless-apigator'
  - serverless-offline

custom:
  apigator:
    entrypoint: lib/handler
    buildFolder: /home/davide/dev/services/packages/groups/lib

# you can overwrite defaults here
  stage: dev
  region: eu-west-2

package:
  exclude:
    ${file(../apigateway/excludes.yml)}
