name: Test+Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: yarn install --frozen-lockfile
      - name: version
        run: yarn tsc -v
      - name: test
        run: yarn test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: yarn install --frozen-lockfile
    - name: build
      run: yarn build
