name: Test+Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: yarn install
      - name: version
        run: yarn tsc -v
      - name: test
        run: yarn test
      - name: uploaad codecoverage
        env: # Or as an environment variable
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: yarn cov:send -t $CODECOV_TOKEN


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: yarn install --frozen-lockfile
    - name: build
      run: yarn build
